development:
  adapter: postgresql
  database: i-instagram
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: i-instagram
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: i-instagram
  pool: 5
  timeout: 5000