# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae3fb3a7ce0b141276b52573601b36f5490723fb640caea82220cee13289a9c69ddfe1fe48285cc81c8ecb751f0d5ef6723fb5e05e2e0bb51132522f542a6cf6
  client_id: 7b5b197214584d648db946e68b79c094
  client_secret: 8b5772632f5b44d9b925be38e1bffb88
  redirect_uri: http://localhost:3000/users/callback

test:
  secret_key_base: 07274f999785204710ea8c9c142c9e8102b9dbe17244bd803a9543f28326c47c08a49ca4f13dc81e627ff5ad6e8b9a3cf8fb1daad33e320bdeec6a3522256b1f
  client_id: 7b5b197214584d648db946e68b79c094
  client_secret: 8b5772632f5b44d9b925be38e1bffb88
  redirect_uri: http://localhost:3000/users/callback

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_id: 7b5b197214584d648db946e68b79c094
  client_secret: 8b5772632f5b44d9b925be38e1bffb88
  redirect_uri: https://immense-ocean-64298.herokuapp.com/users/callback
